In [1]:
#import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers import Conv2D
from keras.layers import MaxPooling2D, Convolution2D
from keras.layers import Activation
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import Dense
#from tensorflow.keras.optimizers import SGD,RMSprop,adam,Adam,Adagrad
from keras import backend as K
from tensorflow.keras.callbacks import TensorBoard
import matplotlib.pyplot as plt
import os
import theano
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import matplotlib
import cv2
from keras.utils import np_utils
import numpy as np
from numpy import *
from tqdm import tqdm
import glob as glob
import imutils

from keras.optimizers import Adam

C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [2]:
p1 = "C:/Users/Harsh Pande/Desktop/Final Mirror Dataset/"
#p2 = "C:/Users/prana/Desktop/DataScience/processed"
img_rows = 40
img_cols = 40

In [3]:
imglist = os.listdir(p1)

In [4]:
n_samples = len(imglist)
print(n_samples)

26097


In [5]:
'''files = glob.glob ("C:/Users/prana/Desktop/DataScience/Final Mirror Dataset/*.jpg")
i = 0
for myFile in files:
    image = cv2.imread (myFile)
    mirror_img = np.fliplr(image)
    #rotated = imutils.rotate(image, 270)
    path = 'C:/Users/prana/Desktop/DataScience/flipped'
    cv2.imwrite(os.path.join(path , "img"+str(i)+".jpg"), mirror_img)
    i = i + 1
'''

'files = glob.glob ("C:/Users/prana/Desktop/DataScience/Final Mirror Dataset/*.jpg")\ni = 0\nfor myFile in files:\n    image = cv2.imread (myFile)\n    mirror_img = np.fliplr(image)\n    #rotated = imutils.rotate(image, 270)\n    path = \'C:/Users/prana/Desktop/DataScience/flipped\'\n    cv2.imwrite(os.path.join(path , "img"+str(i)+".jpg"), mirror_img)\n    i = i + 1\n'

In [6]:
#
import cv2
import glob
import numpy as np

X_data = []
files = glob.glob ("C:/Users/Harsh Pande/Desktop/Final Mirror Dataset/*.jpg")
for myFile in files:
    #print(myFile)
    image = cv2.imread (myFile)
    resized_image = cv2.resize(image, (img_rows,img_cols)) 
    X_data.append (resized_image)

final = np.array(X_data)
final.shape

(26097, 40, 40, 3)

In [7]:
pixel_lists = final.reshape(final.shape[:-3] + (-1, 3))
print(pixel_lists.shape)  

new1 = pixel_lists.reshape((pixel_lists.shape[1]*pixel_lists.shape[2]),pixel_lists.shape[0])
print(new1.shape)
new2 = new1.transpose()
print(new2.shape)



(26097, 1600, 3)
(4800, 26097)
(26097, 4800)


In [8]:
label = np.ones((n_samples,),dtype = int)
label[0:8699] = 0
label[8700:17399] = 1
label[17400:26099] = 2
print(label[5799])

0


In [9]:
data, Label =shuffle(new2,label,random_state=2)
train_data = [data, Label]


In [10]:
print(train_data[0].shape)
print(train_data[1].shape)
print(train_data[0][2][-300:])

(26097, 4800)
(26097,)
[116 255  48 255 156 255 153 186  56 116 252  83 119 127 104  35 159 156
  55 130  69 139 255 133 255 126 255  70 250 114 152 138  95 254 146 242
 110  48 183  49  43 156 101 173  96 255  82 255  31 255 189  82 222 109
 170 126 252 139 255 140 254 108 251 175  27 195  33 101 109 135 109  32
 255 146 177  92 157  68 107 253 153 255 145 255  96 254 114  70  73 102
  13  46  59 131 115 186  38 251  33 175  66 124 255  75 255 215 255 126
 125  60  42  88 171 255  58  68  29  48 132  52  43 170 162 254  74 255
  60 255  54 255  70 192 183  76 149 119 255 159 255  84 235 111 164  97
  47 184  24 107  15  32 104  68 255  68  50 142  20  95  98 255 165 255
 132 255  96 222  96  58 194  21  98 101  87  13  69  68 117  59  57 100
  23 170 255 115 255  85 255 170 205  41  39  39 122 116 137  81 121  60
  28 127  95  89  85 255  55 255 169 255  98 255 116 125  52  62  55  43
 255  75 250 156 155 164 144  93  37 136 146 147 141  77 255 152 255  40
  86  87  56  19 167 255 178

In [11]:
#Parameters
batch_size = 2048
n_epochs = 20
n_classes = 3
img_channel = 3
n_filters = 64
n_filters2 = 32
n_filters3 = 32
n_pool = 2
n_conv = 3

In [12]:
(x , y) = (train_data[0],train_data[1])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.45,random_state=33)


x_train = x_train.reshape(x_train.shape[0],3,img_rows,img_cols)

x_test = x_test.reshape(x_test.shape[0],3,img_rows,img_cols)



x_train = x_train.astype('float32')
x_test = x_test.astype('float32')


x_train /= 255#standardization
x_test /= 255

y_train = np_utils.to_categorical(y_train,n_classes)
y_test = np_utils.to_categorical(y_test,n_classes)

print(y_train)


[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [13]:
#changes1 ===> n_filters, activation,dropout

In [14]:
model  = Sequential()
from time import time

K.set_image_dim_ordering('th')
model.add(Convolution2D(n_filters,n_conv,n_conv,border_mode='valid',input_shape=(3,img_rows,img_cols)))#n_filters should be in power of 2
convout1 = Activation('relu')
model.add(convout1)
model.add(MaxPooling2D(pool_size=(n_pool,n_pool),dim_ordering="th"))
#model.add(Dropout(0.2))#0.119

model.add(Convolution2D(n_filters2,n_conv,n_conv))
convout2 = Activation('relu')#(0,x) if x is neg it will be 0 else whatever is the value of x
model.add(convout2)
model.add(MaxPooling2D(pool_size=(n_pool,n_pool),dim_ordering="th"))
#model.add(Dropout(0.2))

model.add(Convolution2D(n_filters3,n_conv,n_conv))
convout2 = Activation('relu')
model.add(convout2)
model.add(MaxPooling2D(pool_size=(n_pool,n_pool),dim_ordering="th"))
#model.add(Dropout(0.2))

model.add(Flatten())


model.add(Dense(512))   ###Changes- latest
model.add(Activation('relu'))
#model.add(Dropout(0.25))

model.add(Dense(n_classes))  ###Changes
model.add(Dropout(0.25))##changed position

model.add(Activation('softmax'))#e to power of x/summation of e to the power of x(basically gives us the probability)


optimizer = Adam()
model.compile(loss='categorical_crossentropy',optimizer=optimizer ,metrics=['accuracy'])
#tensorboard = TensorBoard(log_dir="./Graph".format(time()))
tensorboard = TensorBoard(log_dir="./Graph", histogram_freq=0, write_graph=True, write_images=True)
#keras.optimizers.Adagrad(lr=0.01, epsilon=None, decay=0.0)
model.summary()

C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), input_shape=(3, 40, 40..., padding="valid")`
  """
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3))`
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:14: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipy

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 64, 38, 38)        1792      
_________________________________________________________________
activation_1 (Activation)    (None, 64, 38, 38)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 64, 19, 19)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 17, 17)        18464     
_________________________________________________________________
activation_2 (Activation)    (None, 32, 17, 17)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 32, 8, 8)          0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 6, 6)          9248      
__________

In [15]:
#history = model.fit(x_train,y_train,batch_size=batch_size,epochs=n_epochs,verbose=1,validation_data=(x_test,y_test), callbacks=[tensorboard])
model.fit(x_train,y_train,batch_size=batch_size,epochs=n_epochs,verbose=1,validation_data=(x_test,y_test), callbacks=[tensorboard])


Train on 14353 samples, validate on 11744 samples
Epoch 1/20
14353/14353 [==============================] - ETA: 2:31 - loss: 1.1080 - acc: 0.332 - ETA: 1:58 - loss: 1.1176 - acc: 0.337 - ETA: 1:31 - loss: 1.1108 - acc: 0.340 - ETA: 1:07 - loss: 1.1070 - acc: 0.342 - ETA: 44s - loss: 1.1057 - acc: 0.340 - ETA: 22s - loss: 1.1039 - acc: 0.34 - ETA: 0s - loss: 1.1027 - acc: 0.3475 - 210s 15ms/step - loss: 1.1027 - acc: 0.3477 - val_loss: 1.1069 - val_acc: 0.3271
Epoch 2/20
14353/14353 [==============================] - ETA: 1:57 - loss: 1.1053 - acc: 0.337 - ETA: 1:34 - loss: 1.1044 - acc: 0.332 - ETA: 1:18 - loss: 1.1019 - acc: 0.338 - ETA: 58s - loss: 1.0998 - acc: 0.342 - ETA: 38s - loss: 1.0990 - acc: 0.34 - ETA: 19s - loss: 1.0979 - acc: 0.34 - ETA: 0s - loss: 1.0973 - acc: 0.3541 - 205s 14ms/step - loss: 1.0973 - acc: 0.3541 - val_loss: 1.0919 - val_acc: 0.3298
Epoch 3/20
14353/14353 [==============================] - ETA: 2:28 - loss: 1.0905 - acc: 0.339 - ETA: 1:55 - loss: 1.0896

14353/14353 [==============================] - ETA: 2:29 - loss: 0.1469 - acc: 0.933 - ETA: 2:04 - loss: 0.1453 - acc: 0.938 - ETA: 1:39 - loss: 0.1446 - acc: 0.935 - ETA: 1:14 - loss: 0.1483 - acc: 0.933 - ETA: 49s - loss: 0.1474 - acc: 0.933 - ETA: 24s - loss: 0.1458 - acc: 0.93 - ETA: 0s - loss: 0.1462 - acc: 0.9322 - 246s 17ms/step - loss: 0.1461 - acc: 0.9323 - val_loss: 0.0517 - val_acc: 0.9881


In [25]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('C:/Users/Harsh Pande/Desktop/Data Science/12.jpg', target_size = (40, 40))
#test_image = test_image.convert("L"
test_image = image.img_to_array(test_image)
#print(test_image.shape)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)



if (result[0][0] > result[0][1]) and (result[0][0] > result[0][2]):
    print("Infant")
if (result[0][1] > result[0][0]) and (result[0][1] > result[0][2]):
    print("Middle")
elif (result[0][2] > result[0][0]) and (result[0][2] > result[0][1]):
    print("Old")
        


print(result)

Middle
[[0. 1. 0.]]


In [40]:
'''import cv2


camera = cv2.VideoCapture(0)

for i in range(1):
    return_value, image = camera.read()
    cv2.imwrite('opencv'+str(i)+'.png', image)


from PIL import Image 
im = Image.open("C:/Users/prana/opencv0.png") 

im.save("C:/Users/prana/img.jpg")


import time

t = 3
time.sleep(t)'''



'''import numpy as np
#from PIL import Image
from keras.preprocessing import image
#test_image = image.load_img("C:/Users/prana/img.jpg", target_size = (40, 40))


test_image = image.load_img("C:/Users/Harsh Pande/Desktop/Data Science/2.jpg", target_size = (40, 40))


#test_image = test_image.convert("L")
test_image = image.img_to_array(test_image)
#print(test_image.shape)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)



if (result[0][0] > result[0][1]) and (result[0][0] > result[0][2]):
    print("Infant")
if (result[0][1] > result[0][0]) and (result[0][1] > result[0][2]):
    print("Middle")
elif (result[0][2] > result[0][0]) and (result[0][2] > result[0][1]):
    print("Old")
        


print(result)


#del(camera)'''

import numpy as np
from PIL import Image
test_image = image.load_img('C:/Users/Harsh Pande/Desktop/Data Science/kid.40.jpg', target_size = (40, 40))
#test_image = test_image.convert("L"
test_image = image.img_to_array(test_image)
#print(test_image.shape)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)



if (result[0][0] > result[0][1]) and (result[0][0] > result[0][2]):
    print("Infant")
if (result[0][1] > result[0][0]) and (result[0][1] > result[0][2]):
    print("Middle")
elif (result[0][2] > result[0][0]) and (result[0][2] > result[0][1]):
    print("Old")
        


print(result)

Middle
[[0. 1. 0.]]


In [ ]:
#list all data in history
"""print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()""""